#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT="$DIR/.."

#if [ "$#" -lt 3 ]; then
#    echo "usage: pass-apply pass-flags in.ll out.ll"
#    exit -1
#fi

NOELLE_NORM="noelle-norm"
NOELLE_LOAD="noelle-load"

PASS_LIB="$ROOT/passes/idempotent-regions/build/idemp-regions.so"
#PASS_FLAGS="-idemp-regions"

#$NOELLE_LOAD "-load $PASS_LIB $PASS_FLAGS -ics-loop-unroll -S  $llvm_norm -o $llvm_pass"
$NOELLE_LOAD "-load $PASS_LIB $PASS_FLAGS -S  $@"
