#!/bin/bash

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ROOT="$DIR/.."

if [ "$#" -ne 2 ]; then
    echo "usage: pass-apply in.ll out.ll"
    exit -1
fi

llvm_norm="$1"
llvm_pass="$2"

NOELLE_NORM="noelle-norm"
NOELLE_LOAD="noelle-load"

PASS_LIB="$ROOT/build/ICS.so"
PASS_FLAGS="-ics"

$NOELLE_LOAD "-load $PASS_LIB $PASS_FLAGS -ics-loop-unroll -S  $llvm_norm -o $llvm_pass"
