#!/bin/bash
# Pass the .elf file (and optional extra arguments) to this script

# Run the ICEmu emulator with the appropriate flags
icemu \
    -p mock_putc_plugin.so \
    -p mock_clockfunc_plugin.so \
    -p instruction_profiling_plugin.so -a instruction-profiling-file=% \
    -p cycle_count_plugin.so -a cycle-count-file=% \
    -p final_value_plugin.so -a final-value=__checkpoint_count \
    -p checkpoint_marker_plugin.so -a checkpoint-marker-file=% \
    -p callsite_count_plugin.so -a callsite-count-track=__checkpoint -a callsite-count-file=% \
    -p checkpoint_verification_plugin.so -a cpval-checkpoint-variable=__lclock -a cpval-ignore-variable=__first_boot -a cpval-uncaught-war-file=% \
    "$@"
