#!/bin/bash
# Take CheckpointVerification WAR report and create a quickfix compatible
# list for use in VIM
#
# WAR report format:
#  description_line_for_columns
#  pc_in_hex, number_of_wars
#  pc_in_hex, number_of_wars
#  ...
#  pc_in_hex, number_of_wars
#
# Quickfix format:
#  filename:line: some text (info)

buffer_file="$1"
war_report=$2

echo "Buffer file: $buffer_file"
echo "Report file: $war_report"

sort -k2 -t',' -r -n "$war_report" | while read line ; do
   content=(${line//,/ })

   addr=${content[0]}
   wars=${content[1]}
   addr="${addr:2}" # remove 0x

   match=$(grep -n "\s*$addr:" "$buffer_file")
   content=(${match//:/ })

   line_nr=${content[0]}

   #echo $line
   #echo $addr
   #echo $wars
   #echo "Found on line: $n"

   echo "$buffer_file:$line_nr:$wars WARs | $match"
done
